version: '3.8'

services:
  mcp-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "23000:3000"
    volumes:
      - ./config.yaml:/app/config.yaml
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge 